Import('env qcheck_lib')

_srcs = Glob('*.d')

_d_link_flags=[File('ConsoleApp.def')]

app = env.Program('test',
                  _srcs,
                  LINKCOM=env['DLINKCOM'],
                  DLINKFLAGS=_d_link_flags,
                  LIBS=[qcheck_lib],
                  DPATH=['#/src', '.'])
Return('app')
