Import('env qcheck_lib')

_srcs = Glob('*.d')

app = env.Program('test',
                  _srcs,
#                  LINKCOM=env['DLINKCOM'],
                  LIBS=[qcheck_lib],
                  LINKFLAGS=env['LINKFLAGS'] + env['DLINKFLAGS'],
                  DPATH=['#/src', '.'])
Return('app')
